"""Move CTA and seasonal_hook to Campaign, add description and website to Advertiser

Revision ID: 8135932d4612
Revises: f2b449ee5798
Create Date: 2026-05-08 10:36:06.491181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8135932d4612'
down_revision = 'f2b449ee5798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.drop_column('cta')
        batch_op.drop_column('seasonal_hook')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seasonal_hook', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('seasonal_hook')
        batch_op.drop_column('cta')

    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seasonal_hook', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('cta', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('website')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
