"""Initial models: Advertiser, Campaign, PronunciationEntry, AdRun

Revision ID: f2b449ee5798
Revises: 
Create Date: 2026-05-08 10:24:19.836050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b449ee5798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('cta', sa.String(length=500), nullable=True),
    sa.Column('seasonal_hook', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('feed_url', sa.String(length=1000), nullable=True),
    sa.Column('feed_config', sa.JSON(), nullable=True),
    sa.Column('target_city', sa.String(length=200), nullable=True),
    sa.Column('voice_preset', sa.String(length=100), nullable=True),
    sa.Column('voice_custom_id', sa.String(length=100), nullable=True),
    sa.Column('music_bed_s3_key', sa.String(length=500), nullable=True),
    sa.Column('music_bed_filename', sa.String(length=200), nullable=True),
    sa.Column('intro_seconds', sa.Float(), nullable=True),
    sa.Column('outro_seconds', sa.Float(), nullable=True),
    sa.Column('duck_volume', sa.Float(), nullable=True),
    sa.Column('duck_fade', sa.Float(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('target_seconds', sa.Integer(), nullable=True),
    sa.Column('target_words', sa.Integer(), nullable=True),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('delivery_enabled', sa.Boolean(), nullable=True),
    sa.Column('delivery_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('voiceover_s3_key', sa.String(length=500), nullable=True),
    sa.Column('final_ad_s3_key', sa.String(length=500), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('feed_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_reference', sa.String(length=500), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronunciation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('written_form', sa.String(length=200), nullable=False),
    sa.Column('spoken_form', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronunciation_entries')
    op.drop_table('ad_runs')
    op.drop_table('campaigns')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
